import ReactGA from 'react-ga4';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GoogleAnalytics from '../../components/common-components/google-analytics';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const TRACKING_ID = "G-6FJPMYFVJ6";
  ReactGA.initialize(TRACKING_ID);
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID={TRACKING_ID} />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
